env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
rules:
  no-console:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
